#!/usr/bin/env bash
# Configures /etc/hosts to make localhost resolve to 127.0.0.2 and facebook.com to 8.8.8.8
grep -v "localhost" /etc/hosts > /tmp/hosts
echo "127.0.0.2 localhost" >> /tmp/hosts
echo "8.8.8.8 facebook.com" >> /tmp/hosts
cat /tmp/hosts > /etc/hosts
