#!/usr/bin/env bash
# Configures /etc/hosts to make localhost resolve to 127.0.0.2 and facebook.com to 8.8.8.8
sed 's/127.0.0.1 localhost/# 127.0.0.1 localhost/' /etc/hosts > /tmp/hosts && cat /tmp/hosts > /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
